"""Configuration settings for the compliance checker."""
import os
from dotenv import load_dotenv

load_dotenv()

# OpenAI Configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o")
EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "text-embedding-3-large")

# Supabase Configuration
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY", "")

# Accredited Laboratories List (from the original implementation)
ACCREDITED_LABORATORIES = [
    'Government Laboratory - Analytical and Advisory Services Division',
    'The Hong Kong Standards and Testing Centre Ltd.',
    'CMA Industrial Development Foundation Limited',
    'Intertek Testing Services Hong Kong Ltd.',
    'Hong Kong Aircraft Engineering Co. Ltd. - Calibration and Metrology Centre',
    'SGS Hong Kong Limited',
    'Civil Engineering and Development Department - Public Works Laboratories',
    'Concrete Services Limited',
    'Hong Kong Testing Company Limited',
    'Fugro Technical Services Limited',
    'Housing Department - Materials Testing Laboratory',
    'Quality Control Consultants Ltd.',
    'Stanger Asia Limited',
    'ETS-Testconsult Limited',
    'Geotechnics & Concrete Engineering (Hong Kong) Ltd.',
    'Labour Department - Occupational Safety and Health Branch - Occupational Hygiene Laboratory',
    'Soils & Materials Engineering Co. Ltd.',
    'Chow Sang Sang Jewellery Co. Ltd. - Chow Sang Sang Precious Metal Laboratory',
    'Castco Testing Centre Ltd.',
    'UL VS Hong Kong Limited',
    'Green Island Cement Company Limited',
    'Hong Kong Productivity Council – Green Living Laboratory',
    'The Hong Kong Jockey Club - Racing Laboratory',
    'Anderson Asphalt Ltd. - Tap Shek Kok Laboratory',
    'K. Wah Asphalt Limited - Man Kam To Road Depot Laboratory',
    'Intertek Testing Services Shenzhen Ltd.',
    'The Government of the Hong Kong Special Administrative Region - Standards and Calibration Laboratory',
    'Gammon Construction Limited – Technology Centre',
    'Bureau Veritas Hong Kong Limited - Kowloon Bay Office',
    'Hong Kong Productivity Council – Smart Manufacturing Division, Materials Testing Laboratory',
    'Environmental Protection Department - Air Services Laboratory',
    'ALS Technichem (HK) Pty Limited',
    'Veolia Environmental Services (Hong Kong) Limited - WENT Environmental Laboratory (WENTLAB)',
    'China Dragon Inspection and Certification (H.K.) Ltd.',
    'Water Supplies Department - New Territories East Regional Laboratory',
    'FT Laboratories Limited',
    'TÜV Rheinland Hong Kong Limited',
    'Water Supplies Department - Meter Testing Laboratory',
    'South China National Centre of Metrology',
    'SGS-CSTC Standards Technical Services Co., Ltd. Shenzhen Branch',
    'Hong Kong Productivity Council - Electromagnetic Compatibility Centre',
    'Wellab Limited',
    'Mattel Toys Technical Consultancy (SZ) Ltd. – Quality Lab',
    'Research Engineering Development Facade Consultants Ltd. - Fire and Facade Testing Laboratory',
    'Quality Testing Services Limited',
    'The Hong Kong University of Science & Technology - Health, Safety and Environment Office Laboratory',
    'Drainage Services Department, Laboratory Services Sub-division - Shatin Central Laboratory',
    'Drainage Services Department - Sewage Services Branch Operation Section Laboratory',
    'CLP Power Hong Kong Ltd. - Generation Central Laboratories',
    'Facadetech Laboratory Ltd.',
    'A.E.S. Destructive and Non-Destructive Testing Limited',
    'Linde HKO Limited – Quality Control Laboratory',
    'Hong Kong Calibration Limited',
    'Hong Kong Curtain Wall Testing Centre Ltd.',
    'JAS (Inspection & Testing) Limited',
    'Water Supplies Department - Pak Kong Water Treatment Works Laboratory',
    'Macau Cement Manufacturing Co. Ltd.',
    'Vitasoy International Holdings Ltd. – Laboratory Management',
    'Acoustics and Air Testing Laboratory Co. Ltd.',
    'The Hong Kong University of Science and Technology - Department of Mechanical and Aerospace Engineering - Jockey Club Controlled Environment Test Facility',
    'Lee Kum Kee Company Limited – Testing Laboratory',
    'Enviro Labs Limited',
    'Eurofins MTS Consumer Product Testing Hong Kong Limited',
    'Nutek Systems (HK) Limited',
    'Wilson Curtain Wall Consultant (HK) Limited',
    'Building Diagnostic Consultants Limited',
    'PROVA Inspection & Testing Co. (HK) Limited',
    'Food and Environmental Hygiene Department - Man Kam To Food Laboratory',
    'C & K Instrument (HK) Limited - Calibration Services Centre',
    'The Chinese University of Hong Kong - School of Pharmacy - Bioanalytical Unit',
    'Sam Hing Scales Factory Limited - Testing and Calibration Laboratory',
    'Prima Technical Services Limited',
    'Food and Environmental Hygiene Department - Food Research Laboratory',
    'Asian Gemmological Institute and Laboratory Limited',
    'China Gems Laboratory Limited',
    'Hong Kong Jade & Stone Laboratory Limited',
    'Pharmtech (Hong Kong) Limited - Quality Control Laboratory',
    'Hong Kong Gems Laboratory Company Limited',
    'HILTI (Hong Kong) Ltd. – Testing Laboratory',
    'CTC Asia Limited',
    'API Lab Testing Limited',
    'Far East Technical Services Limited',
    'MaxLab Calibration Centre Limited - Calibration Laboratory',
    'Excel Building Diagnostic & Inspection Services Limited',
    'Fugro Technical Services (Guangzhou) Limited',
    'Modern Testing Consultants Limited',
    'Acoustic Testing Services Limited',
    'South China Inspection & Testing Limited',
    'Water Supplies Department - Tai Po Water Treatment Works Laboratory',
    'Hong Kong Baptist University – Chemical Testing Services',
    'Qualitech Testing & Consultancy Limited',
    'Consumer Testing Laboratories (Far East) Ltd.',
    'PARKnSHOP (HK) Limited - Safety Laboratory',
    'CAC (Hong Kong) Gems Laboratory Ltd.',
    'Forte Testing and Consultants Company Limited',
    'Promet Metals Testing Laboratory Limited',
    'Ecospace Limited - Laboratory',
    'Water Supplies Department – New Territories West Regional Laboratory',
    'Leading Edge Construction Materials Testing Company Limited',
    'Global Tests Limited',
    'QIMA Testing (HK) Limited',
    'Government Laboratory - Forensic Science Division',
    'The Lab (Asia) Limited',
    'Tech-co (Testing Services) Ltd.',
    'Foodscan Analytics Ltd.',
    'Advance Laboratory and Testing Services Limited',
    'Heraeus Limited - Laboratory Department',
    'Chow Tai Fook Jewellery Co. Ltd. -  Chow Tai Fook Fei Cui Testing Centre',
    'T M Testing Company Limited',
    "Maxim's Caterers Limited - Maxim's Food Factory  - Microbiological Laboratory",
    'K & N Technical Service Co. Limited',
    'Infrared Engineering & Consultants Limited',
    'ASTAR NDT CONSULTANTS LTD',
    'SGS-CSTC Standards Technical Services Co., Ltd. Guangzhou Branch',
    'Smith & Associates Far East Limited – Counterfeit Detection Laboratory',
    'Foundation Testing Services Limited',
    'Hong Kong Precious Metals Assay Centre Ltd',
    'TÜV SÜD Hong Kong Limited',
    'AQuality TestConsult Limited',
    'Shiu Wing Steel Limited - MillBorne Laboratory',
    'Hospital Authority - Medical Equipment Calibration Laboratory',
    'Acumen Laboratory and Testing Limited',
    'Eurofins Food Testing Hong Kong Limited',
    'Hong Kong Institute of Medical Laboratory Sciences - Quality Assurance Programme Limited',
    'Jesee Inspection Technology Co., Ltd.',
    'Union Professional Test-Consult Limited',
    'Zenith Testing & Consultancy Limited',
    'FSE Environmental Laboratory Services Limited',
    'SENSE Engineering Services Co., Ltd.',
    'Japan Recreation and Miscellaneous Goods Safety Laboratory - Hong Kong Office (MGSL HK)',
    'Wai Fat Pharmaceutical Laboratory Limited',
    'JFC Testing and Inspection Company Limited',
    'Quality Pro Test-Consult Limited',
    'HK Elements Limited – Quality Testing Center',
    'Shenzhen Mingji Testing Technology Co., Ltd.',
    'V2 Consulting Limited',
    'Soil Services Testing Company Limited',
    'Hong Kong Productivity Council - Reliability Testing Centre',
    'Appleone Calibration Laboratory Limited',
    'Hong Kong Police Force - Identification Bureau',
    'IDEAL Test Consultants Ltd.',
    'Material Tech Company Limited',
    'Ariken Biotech Japan Testing Laboratory Co., Ltd.,',
    'MINSEN Testing (Hong Kong) Limited',
    'Independent Testing Engineering Limited',
    'Hong Kong Gemological Research and Authentication Centre Company Limited',
    'Hong Kong Baptist University - Research Centre for Standardization of Chinese Medicines',
    '深圳市力信特檢測科技有限公司',
    'Aspec (HK) Limited - Aspec Testing',
    'Laboratory Specialist Co., Limited',
    'AA Lab Limited',
    "Lee's Pharm Genomics Lab Limited",
    'Alliance Testing (HK) Co., Limited',
    'Sky Professional Testing & Consulting Limited',
    'Professional Testing Consultant Limited',
    'Agriculture, Fisheries and Conservation Department - Veterinary Laboratory Division - Tai Lung Veterinary Laboratory',
    'Abidance Testconsult Limited',
    'High Precision Chemical Testing Limited',
    'Technology Solution Testing Limited',
    'Labtech Testing Limited',
    'Gilson China Limited - Gilson Hong Kong Laboratory',
    'Labon Testing Limited',
    'Water Supplies Department - Material Testing Laboratory',
    'ESG Matters Limited – Acoustic Calibration Centre',
    'Department of Health - Regulatory Affairs, Chinese Medicine Regulatory Office, Government Chinese Medicines Testing Institute',
    'Honest Testing Services Limited',
    'Acurweight Technology Limited',
    'Sartorius Hong Kong Limited - Calibration Laboratory',
    '東莞兆閔帷幕牆有限公司',
    'KAS Quality Service (Guangzhou) Co., Ltd',
    'Weldtech Inspection & Testing Limited',
    'LUX Environmental Service Company Limited - Lux Laboratory',
    'AICON Company Limited',
    'Fugro MateriaLab Services Limited',
    'Hong Kong Authentication Centre of Valuable Chinese Medicines Limited',
    'Bioenergy Resources Research Centre Limited',
    'Westwood Hong & Associates Limited',
    'Guangdong Construction Engineering Quality & Safety Testing Head Station Co., Ltd',
    'New Creation Calibration Service Limited',
    'Department of Health - Centre for Health Protection, Public Health Laboratory Services Branch, Microbiology Division',
    'Diagnostix Pathology Laboratories Ltd.',
    'Department of Health - Centre for Health Protection, Public Health Laboratory Services Branch, Histopathology and Cytology Division',
    'PathLab Medical Laboratories Limited',
    'Diagnostix Medical Centre Ltd.',
    'Hospital Authority - Alice Ho Miu Ling Nethersole Hospital, Department of Pathology',
    'Hospital Authority - North District Hospital, Department of Pathology',
    """St. Teresa's Hospital – Histopathology Laboratory""",
    'Department of Health - Centre for Health Protection, Public Health Laboratory Services Branch, Chemical Pathology and Haematology Division',
    'Hospital Authority - Tseung Kwan O Hospital, Department of Pathology',
    'Hospital Authority - Hong Kong Red Cross Blood Transfusion Service',
    'Hospital Authority - United Christian Hospital, Department of Pathology',
    'Quality Healthcare Medical Services Limited – Alpha Medical Diagnostic Centre',
    'Hospital Authority - Hong Kong East Cluster, Department of Clinical Pathology',
    'KingMed Diagnostics (Hong Kong) Limited',
    'Onco Medical Laboratory Ltd.',
    'Seventh- Day Adventist Corporation (HK) Limited - Clinical Laboratories, Adventist Health',
    'Hospital Authority - Princess Margaret Hospital, Department of Pathology',
    'Hospital Authority - Yan Chai Hospital, Department of Pathology',
    'Hospital Authority - Caritas Medical Centre, Department of Clinical Pathology',
    'Hospital Authority - Tsan Yuk Hospital, Prenatal Diagnostic Laboratory',
    'Hospital Authority - Kwong Wah Hospital, Department of Pathology',
    'Chan & Hou Medical Laboratories Ltd.',
    'Canossa Hospital (Caritas) Management Company Limited - Clinical Laboratory',
    'Hospital Authority - Tuen Mun Hospital, Department of Clinical Pathology',
    'Hong Kong Molecular Pathology Diagnostic Centre Limited',
    'iPath Laboratory Limited',
    'The Chinese University of Hong Kong - Department of Obstetrics and Gynaecology, Obstetrics Screening Laboratory',
    'GHK Hospital Limited – Gleneagles Hospital Hong Kong, Department of Clinical Laboratory',
    'Hong Kong Baptist Hospital - Pathology Department',
    'Hong Kong Health Check and Medical Diagnostic Centre Limited - Hong Kong Health Check Medical Laboratory',
    "St. Paul's Hospital - Pathology Department",
    'Precious Blood Hospital (Caritas) - Clinical Pathology Laboratory',
    'Xcelom Limited - Xcelom Microbiology Laboratory',
    'HKSH Medical Group Limited - Department of Pathology',
    'The Hong Kong Polytechnic University - Molecular Diagnostic Laboratory',
    'FZ Public Health Laboratory Company Limited',
    'Medtimes Molecular Laboratory Limited',
    'CUHK Medical Centre - Department of Pathology',
    "Lee's Pharm Genomics Lab Limited",
    "St. Teresa's Hospital - Clinical Laboratory",
    'Pangenia Lifesciences Limited',
    'Evangel Hospital - Laboratory',
    'Hong Kong Precision Pathology Laboratory Limited',
    'New Life Laboratory Testing Limited',
    'Hospital Authority – Queen Elizabeth Hospital, Department of Pathology ',
    'In Touch, Limited – Histopathology Laboratory',
    'Codex Genetics Limited',
    'Bright Growth Medical Laboratory Limited',
    "Hospital Authority - Hong Kong Children's Hospital, Department of Pathology",
    'GenieBiome (Diagnostic) Co. Ltd. - G-NiiB Molecular & MicroBiome Laboratory',
]

# Processing Configuration
CHUNK_SIZE = 1000  # Characters per chunk
CHUNK_OVERLAP = 200  # Overlap between chunks
BATCH_SIZE = 3  # Number of requirements to process in parallel
TOP_K_CHUNKS = 8  # Number of document chunks to retrieve per requirement

# Data Storage
DATA_DIR = "data"
DOCUMENTS_DIR = os.path.join(DATA_DIR, "documents")
PROJECTS_DIR = os.path.join(DATA_DIR, "projects")

